name: Style Check

on:
  pull_request:
    branches: [ "*" ]

jobs:
  style-check:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SwiftLint and SwiftFormat
        run: |
          brew install swiftlint swiftformat

      - name: Check SwiftFormat
        working-directory: Project
        run: |
          swiftformat hideandseek --config .swiftformat --lint

      - name: Check SwiftLint
        working-directory: Project
        run: |
          swiftlint --config swiftlint.yml hideandseek